# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ace.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tace.proto\x12\x03\x61\x63\x65\"7\n\x0fSyllabusRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"_\n\x10SyllabusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rnodes_created\x18\x03 \x01(\x05\x12\x12\n\ngraph_json\x18\x04 \x01(\t\"2\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\" \n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t2{\n\x0cTutorService\x12>\n\x0fProcessSyllabus\x12\x14.ace.SyllabusRequest\x1a\x15.ace.SyllabusResponse\x12+\n\x04\x43hat\x12\x10.ace.ChatRequest\x1a\x11.ace.ChatResponseB\nZ\x08pb/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010pb/proto'
  _globals['_SYLLABUSREQUEST']._serialized_start=18
  _globals['_SYLLABUSREQUEST']._serialized_end=73
  _globals['_SYLLABUSRESPONSE']._serialized_start=75
  _globals['_SYLLABUSRESPONSE']._serialized_end=170
  _globals['_CHATREQUEST']._serialized_start=172
  _globals['_CHATREQUEST']._serialized_end=222
  _globals['_CHATRESPONSE']._serialized_start=224
  _globals['_CHATRESPONSE']._serialized_end=256
  _globals['_TUTORSERVICE']._serialized_start=258
  _globals['_TUTORSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
