# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ace_pb2 as ace__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TutorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSyllabus = channel.unary_unary(
                '/ace.TutorService/ProcessSyllabus',
                request_serializer=ace__pb2.SyllabusRequest.SerializeToString,
                response_deserializer=ace__pb2.SyllabusResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/ace.TutorService/Chat',
                request_serializer=ace__pb2.ChatRequest.SerializeToString,
                response_deserializer=ace__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.SubmitQuizResult = channel.unary_unary(
                '/ace.TutorService/SubmitQuizResult',
                request_serializer=ace__pb2.QuizResultRequest.SerializeToString,
                response_deserializer=ace__pb2.QuizResultResponse.FromString,
                _registered_method=True)
        self.GenerateAdaptiveQuiz = channel.unary_unary(
                '/ace.TutorService/GenerateAdaptiveQuiz',
                request_serializer=ace__pb2.AdaptiveQuizRequest.SerializeToString,
                response_deserializer=ace__pb2.AdaptiveQuizResponse.FromString,
                _registered_method=True)
        self.GetQuizScores = channel.unary_unary(
                '/ace.TutorService/GetQuizScores',
                request_serializer=ace__pb2.GetQuizScoresRequest.SerializeToString,
                response_deserializer=ace__pb2.GetQuizScoresResponse.FromString,
                _registered_method=True)
        self.IngestMaterial = channel.unary_unary(
                '/ace.TutorService/IngestMaterial',
                request_serializer=ace__pb2.IngestRequest.SerializeToString,
                response_deserializer=ace__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.GenerateQuiz = channel.unary_unary(
                '/ace.TutorService/GenerateQuiz',
                request_serializer=ace__pb2.QuizRequest.SerializeToString,
                response_deserializer=ace__pb2.QuizResponse.FromString,
                _registered_method=True)
        self.GenerateCramSession = channel.unary_unary(
                '/ace.TutorService/GenerateCramSession',
                request_serializer=ace__pb2.CramRequest.SerializeToString,
                response_deserializer=ace__pb2.CramResponse.FromString,
                _registered_method=True)
        self.GenerateLesson = channel.unary_unary(
                '/ace.TutorService/GenerateLesson',
                request_serializer=ace__pb2.LessonRequest.SerializeToString,
                response_deserializer=ace__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.GenerateLessonAndExercises = channel.unary_unary(
                '/ace.TutorService/GenerateLessonAndExercises',
                request_serializer=ace__pb2.LessonRequest.SerializeToString,
                response_deserializer=ace__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.CheckTopicSufficiency = channel.unary_unary(
                '/ace.TutorService/CheckTopicSufficiency',
                request_serializer=ace__pb2.SufficiencyRequest.SerializeToString,
                response_deserializer=ace__pb2.SufficiencyResponse.FromString,
                _registered_method=True)


class TutorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessSyllabus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitQuizResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAdaptiveQuiz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuizScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestMaterial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateQuiz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCramSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateLesson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateLessonAndExercises(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTopicSufficiency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSyllabus': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSyllabus,
                    request_deserializer=ace__pb2.SyllabusRequest.FromString,
                    response_serializer=ace__pb2.SyllabusResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ace__pb2.ChatRequest.FromString,
                    response_serializer=ace__pb2.ChatResponse.SerializeToString,
            ),
            'SubmitQuizResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitQuizResult,
                    request_deserializer=ace__pb2.QuizResultRequest.FromString,
                    response_serializer=ace__pb2.QuizResultResponse.SerializeToString,
            ),
            'GenerateAdaptiveQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAdaptiveQuiz,
                    request_deserializer=ace__pb2.AdaptiveQuizRequest.FromString,
                    response_serializer=ace__pb2.AdaptiveQuizResponse.SerializeToString,
            ),
            'GetQuizScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuizScores,
                    request_deserializer=ace__pb2.GetQuizScoresRequest.FromString,
                    response_serializer=ace__pb2.GetQuizScoresResponse.SerializeToString,
            ),
            'IngestMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMaterial,
                    request_deserializer=ace__pb2.IngestRequest.FromString,
                    response_serializer=ace__pb2.IngestResponse.SerializeToString,
            ),
            'GenerateQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuiz,
                    request_deserializer=ace__pb2.QuizRequest.FromString,
                    response_serializer=ace__pb2.QuizResponse.SerializeToString,
            ),
            'GenerateCramSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCramSession,
                    request_deserializer=ace__pb2.CramRequest.FromString,
                    response_serializer=ace__pb2.CramResponse.SerializeToString,
            ),
            'GenerateLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLesson,
                    request_deserializer=ace__pb2.LessonRequest.FromString,
                    response_serializer=ace__pb2.LessonResponse.SerializeToString,
            ),
            'GenerateLessonAndExercises': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLessonAndExercises,
                    request_deserializer=ace__pb2.LessonRequest.FromString,
                    response_serializer=ace__pb2.LessonResponse.SerializeToString,
            ),
            'CheckTopicSufficiency': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTopicSufficiency,
                    request_deserializer=ace__pb2.SufficiencyRequest.FromString,
                    response_serializer=ace__pb2.SufficiencyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ace.TutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ace.TutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TutorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSyllabus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/ProcessSyllabus',
            ace__pb2.SyllabusRequest.SerializeToString,
            ace__pb2.SyllabusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/Chat',
            ace__pb2.ChatRequest.SerializeToString,
            ace__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitQuizResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/SubmitQuizResult',
            ace__pb2.QuizResultRequest.SerializeToString,
            ace__pb2.QuizResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAdaptiveQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/GenerateAdaptiveQuiz',
            ace__pb2.AdaptiveQuizRequest.SerializeToString,
            ace__pb2.AdaptiveQuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuizScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/GetQuizScores',
            ace__pb2.GetQuizScoresRequest.SerializeToString,
            ace__pb2.GetQuizScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/IngestMaterial',
            ace__pb2.IngestRequest.SerializeToString,
            ace__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/GenerateQuiz',
            ace__pb2.QuizRequest.SerializeToString,
            ace__pb2.QuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCramSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/GenerateCramSession',
            ace__pb2.CramRequest.SerializeToString,
            ace__pb2.CramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/GenerateLesson',
            ace__pb2.LessonRequest.SerializeToString,
            ace__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateLessonAndExercises(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/GenerateLessonAndExercises',
            ace__pb2.LessonRequest.SerializeToString,
            ace__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckTopicSufficiency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/CheckTopicSufficiency',
            ace__pb2.SufficiencyRequest.SerializeToString,
            ace__pb2.SufficiencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
