# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ace_pb2 as ace__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSyllabus = channel.unary_unary(
                '/ace.TutorService/ProcessSyllabus',
                request_serializer=ace__pb2.SyllabusRequest.SerializeToString,
                response_deserializer=ace__pb2.SyllabusResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/ace.TutorService/Chat',
                request_serializer=ace__pb2.ChatRequest.SerializeToString,
                response_deserializer=ace__pb2.ChatResponse.FromString,
                _registered_method=True)


class TutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessSyllabus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSyllabus': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSyllabus,
                    request_deserializer=ace__pb2.SyllabusRequest.FromString,
                    response_serializer=ace__pb2.SyllabusResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ace__pb2.ChatRequest.FromString,
                    response_serializer=ace__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ace.TutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ace.TutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSyllabus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/ProcessSyllabus',
            ace__pb2.SyllabusRequest.SerializeToString,
            ace__pb2.SyllabusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ace.TutorService/Chat',
            ace__pb2.ChatRequest.SerializeToString,
            ace__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
