// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/ace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyllabusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,4,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusRequest) Reset() {
	*x = SyllabusRequest{}
	mi := &file_proto_ace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusRequest) ProtoMessage() {}

func (x *SyllabusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusRequest.ProtoReflect.Descriptor instead.
func (*SyllabusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{0}
}

func (x *SyllabusRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SyllabusRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *SyllabusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyllabusRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *SyllabusRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type SyllabusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodesCreated  int32                  `protobuf:"varint,3,opt,name=nodes_created,json=nodesCreated,proto3" json:"nodes_created,omitempty"`
	GraphJson     string                 `protobuf:"bytes,4,opt,name=graph_json,json=graphJson,proto3" json:"graph_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusResponse) Reset() {
	*x = SyllabusResponse{}
	mi := &file_proto_ace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusResponse) ProtoMessage() {}

func (x *SyllabusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusResponse.ProtoReflect.Descriptor instead.
func (*SyllabusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{1}
}

func (x *SyllabusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyllabusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyllabusResponse) GetNodesCreated() int32 {
	if x != nil {
		return x.NodesCreated
	}
	return 0
}

func (x *SyllabusResponse) GetGraphJson() string {
	if x != nil {
		return x.GraphJson
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                      // The user's question
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // To track conversation history later
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,4,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_ace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // The AI's answer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_ace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// Sent by UI when a student finishes a quiz
type QuizResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	ClassId       string                 `protobuf:"bytes,4,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResultRequest) Reset() {
	*x = QuizResultRequest{}
	mi := &file_proto_ace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultRequest) ProtoMessage() {}

func (x *QuizResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultRequest.ProtoReflect.Descriptor instead.
func (*QuizResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{4}
}

func (x *QuizResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizResultRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *QuizResultRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizResultRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type QuizResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResultResponse) Reset() {
	*x = QuizResultResponse{}
	mi := &file_proto_ace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultResponse) ProtoMessage() {}

func (x *QuizResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultResponse.ProtoReflect.Descriptor instead.
func (*QuizResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{5}
}

func (x *QuizResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QuizResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sent by UI when a student clicks "Generate Review Quiz"
type AdaptiveQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SyllabusName  string                 `protobuf:"bytes,2,opt,name=syllabus_name,json=syllabusName,proto3" json:"syllabus_name,omitempty"` // Which class are they studying for?
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptiveQuizRequest) Reset() {
	*x = AdaptiveQuizRequest{}
	mi := &file_proto_ace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveQuizRequest) ProtoMessage() {}

func (x *AdaptiveQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveQuizRequest.ProtoReflect.Descriptor instead.
func (*AdaptiveQuizRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{6}
}

func (x *AdaptiveQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdaptiveQuizRequest) GetSyllabusName() string {
	if x != nil {
		return x.SyllabusName
	}
	return ""
}

func (x *AdaptiveQuizRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

// We can reuse ChatResponse for the quiz return, or make a specific one:
type AdaptiveQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizJson      string                 `protobuf:"bytes,1,opt,name=quiz_json,json=quizJson,proto3" json:"quiz_json,omitempty"` // Gemini's strict JSON output of questions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptiveQuizResponse) Reset() {
	*x = AdaptiveQuizResponse{}
	mi := &file_proto_ace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveQuizResponse) ProtoMessage() {}

func (x *AdaptiveQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveQuizResponse.ProtoReflect.Descriptor instead.
func (*AdaptiveQuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{7}
}

func (x *AdaptiveQuizResponse) GetQuizJson() string {
	if x != nil {
		return x.QuizJson
	}
	return ""
}

// Sent by UI to read student performance/scores
type GetQuizScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizScoresRequest) Reset() {
	*x = GetQuizScoresRequest{}
	mi := &file_proto_ace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizScoresRequest) ProtoMessage() {}

func (x *GetQuizScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizScoresRequest.ProtoReflect.Descriptor instead.
func (*GetQuizScoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{8}
}

func (x *GetQuizScoresRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetQuizScoresRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type QuizScoreRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClassId       string                 `protobuf:"bytes,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizScoreRecord) Reset() {
	*x = QuizScoreRecord{}
	mi := &file_proto_ace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizScoreRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizScoreRecord) ProtoMessage() {}

func (x *QuizScoreRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizScoreRecord.ProtoReflect.Descriptor instead.
func (*QuizScoreRecord) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{9}
}

func (x *QuizScoreRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizScoreRecord) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *QuizScoreRecord) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizScoreRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *QuizScoreRecord) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type GetQuizScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*QuizScoreRecord     `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizScoresResponse) Reset() {
	*x = GetQuizScoresResponse{}
	mi := &file_proto_ace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizScoresResponse) ProtoMessage() {}

func (x *GetQuizScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizScoresResponse.ProtoReflect.Descriptor instead.
func (*GetQuizScoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuizScoresResponse) GetScores() []*QuizScoreRecord {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *GetQuizScoresResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetQuizScoresResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    int32                  `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	RawText       string                 `protobuf:"bytes,3,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,6,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,7,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,8,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_ace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{11}
}

func (x *IngestRequest) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *IngestRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *IngestRequest) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *IngestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IngestRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *IngestRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *IngestRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *IngestRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_ace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{12}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QuizRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber         int32                  `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	QuestionCount      int32                  `protobuf:"varint,2,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Regenerate         bool                   `protobuf:"varint,4,opt,name=regenerate,proto3" json:"regenerate,omitempty"`
	RegenerationPrompt string                 `protobuf:"bytes,5,opt,name=regeneration_prompt,json=regenerationPrompt,proto3" json:"regeneration_prompt,omitempty"`
	WeakTopics         []string               `protobuf:"bytes,6,rep,name=weak_topics,json=weakTopics,proto3" json:"weak_topics,omitempty"`
	ClassId            string                 `protobuf:"bytes,7,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuizRequest) Reset() {
	*x = QuizRequest{}
	mi := &file_proto_ace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizRequest) ProtoMessage() {}

func (x *QuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizRequest.ProtoReflect.Descriptor instead.
func (*QuizRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{13}
}

func (x *QuizRequest) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *QuizRequest) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *QuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizRequest) GetRegenerate() bool {
	if x != nil {
		return x.Regenerate
	}
	return false
}

func (x *QuizRequest) GetRegenerationPrompt() string {
	if x != nil {
		return x.RegenerationPrompt
	}
	return ""
}

func (x *QuizRequest) GetWeakTopics() []string {
	if x != nil {
		return x.WeakTopics
	}
	return nil
}

func (x *QuizRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type Question struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionText       string                 `protobuf:"bytes,2,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	Options            []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	CorrectOptionIndex int32                  `protobuf:"varint,4,opt,name=correct_option_index,json=correctOptionIndex,proto3" json:"correct_option_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_ace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{14}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetCorrectOptionIndex() int32 {
	if x != nil {
		return x.CorrectOptionIndex
	}
	return 0
}

type QuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResponse) Reset() {
	*x = QuizResponse{}
	mi := &file_proto_ace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponse) ProtoMessage() {}

func (x *QuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponse.ProtoReflect.Descriptor instead.
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{15}
}

func (x *QuizResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartWeek     int32                  `protobuf:"varint,2,opt,name=start_week,json=startWeek,proto3" json:"start_week,omitempty"`
	EndWeek       int32                  `protobuf:"varint,3,opt,name=end_week,json=endWeek,proto3" json:"end_week,omitempty"`
	WeakTopics    []string               `protobuf:"bytes,4,rep,name=weak_topics,json=weakTopics,proto3" json:"weak_topics,omitempty"`
	ClassId       string                 `protobuf:"bytes,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CramRequest) Reset() {
	*x = CramRequest{}
	mi := &file_proto_ace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CramRequest) ProtoMessage() {}

func (x *CramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CramRequest.ProtoReflect.Descriptor instead.
func (*CramRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{16}
}

func (x *CramRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CramRequest) GetStartWeek() int32 {
	if x != nil {
		return x.StartWeek
	}
	return 0
}

func (x *CramRequest) GetEndWeek() int32 {
	if x != nil {
		return x.EndWeek
	}
	return 0
}

func (x *CramRequest) GetWeakTopics() []string {
	if x != nil {
		return x.WeakTopics
	}
	return nil
}

func (x *CramRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type CramResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DenseReviewMarkdown string                 `protobuf:"bytes,1,opt,name=dense_review_markdown,json=denseReviewMarkdown,proto3" json:"dense_review_markdown,omitempty"`
	RapidFireQuiz       []*Question            `protobuf:"bytes,2,rep,name=rapid_fire_quiz,json=rapidFireQuiz,proto3" json:"rapid_fire_quiz,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CramResponse) Reset() {
	*x = CramResponse{}
	mi := &file_proto_ace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CramResponse) ProtoMessage() {}

func (x *CramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CramResponse.ProtoReflect.Descriptor instead.
func (*CramResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{17}
}

func (x *CramResponse) GetDenseReviewMarkdown() string {
	if x != nil {
		return x.DenseReviewMarkdown
	}
	return ""
}

func (x *CramResponse) GetRapidFireQuiz() []*Question {
	if x != nil {
		return x.RapidFireQuiz
	}
	return nil
}

type LessonRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber         int32                  `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WeakTopics         []string               `protobuf:"bytes,3,rep,name=weak_topics,json=weakTopics,proto3" json:"weak_topics,omitempty"`
	Regenerate         bool                   `protobuf:"varint,4,opt,name=regenerate,proto3" json:"regenerate,omitempty"`
	RegenerationPrompt string                 `protobuf:"bytes,5,opt,name=regeneration_prompt,json=regenerationPrompt,proto3" json:"regeneration_prompt,omitempty"`
	ClassId            string                 `protobuf:"bytes,6,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LessonRequest) Reset() {
	*x = LessonRequest{}
	mi := &file_proto_ace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonRequest) ProtoMessage() {}

func (x *LessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonRequest.ProtoReflect.Descriptor instead.
func (*LessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{18}
}

func (x *LessonRequest) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *LessonRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LessonRequest) GetWeakTopics() []string {
	if x != nil {
		return x.WeakTopics
	}
	return nil
}

func (x *LessonRequest) GetRegenerate() bool {
	if x != nil {
		return x.Regenerate
	}
	return false
}

func (x *LessonRequest) GetRegenerationPrompt() string {
	if x != nil {
		return x.RegenerationPrompt
	}
	return ""
}

func (x *LessonRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type LessonResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LessonMarkdown        string                 `protobuf:"bytes,1,opt,name=lesson_markdown,json=lessonMarkdown,proto3" json:"lesson_markdown,omitempty"`
	Exercises             []*Question            `protobuf:"bytes,2,rep,name=exercises,proto3" json:"exercises,omitempty"`
	InsufficientMaterials bool                   `protobuf:"varint,3,opt,name=insufficient_materials,json=insufficientMaterials,proto3" json:"insufficient_materials,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LessonResponse) Reset() {
	*x = LessonResponse{}
	mi := &file_proto_ace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonResponse) ProtoMessage() {}

func (x *LessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonResponse.ProtoReflect.Descriptor instead.
func (*LessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{19}
}

func (x *LessonResponse) GetLessonMarkdown() string {
	if x != nil {
		return x.LessonMarkdown
	}
	return ""
}

func (x *LessonResponse) GetExercises() []*Question {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *LessonResponse) GetInsufficientMaterials() bool {
	if x != nil {
		return x.InsufficientMaterials
	}
	return false
}

type SufficiencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	WeekNumber    int32                  `protobuf:"varint,3,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SufficiencyRequest) Reset() {
	*x = SufficiencyRequest{}
	mi := &file_proto_ace_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SufficiencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SufficiencyRequest) ProtoMessage() {}

func (x *SufficiencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SufficiencyRequest.ProtoReflect.Descriptor instead.
func (*SufficiencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{20}
}

func (x *SufficiencyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SufficiencyRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *SufficiencyRequest) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

type SufficiencyResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	InsufficientMaterials bool                   `protobuf:"varint,1,opt,name=insufficient_materials,json=insufficientMaterials,proto3" json:"insufficient_materials,omitempty"`
	InsufficientTopics    []string               `protobuf:"bytes,2,rep,name=insufficient_topics,json=insufficientTopics,proto3" json:"insufficient_topics,omitempty"`
	AllTopics             []string               `protobuf:"bytes,3,rep,name=all_topics,json=allTopics,proto3" json:"all_topics,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SufficiencyResponse) Reset() {
	*x = SufficiencyResponse{}
	mi := &file_proto_ace_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SufficiencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SufficiencyResponse) ProtoMessage() {}

func (x *SufficiencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SufficiencyResponse.ProtoReflect.Descriptor instead.
func (*SufficiencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{21}
}

func (x *SufficiencyResponse) GetInsufficientMaterials() bool {
	if x != nil {
		return x.InsufficientMaterials
	}
	return false
}

func (x *SufficiencyResponse) GetInsufficientTopics() []string {
	if x != nil {
		return x.InsufficientTopics
	}
	return nil
}

func (x *SufficiencyResponse) GetAllTopics() []string {
	if x != nil {
		return x.AllTopics
	}
	return nil
}

type DeleteClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClassRequest) Reset() {
	*x = DeleteClassRequest{}
	mi := &file_proto_ace_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassRequest) ProtoMessage() {}

func (x *DeleteClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassRequest.ProtoReflect.Descriptor instead.
func (*DeleteClassRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteClassRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteClassRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type DeleteClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClassResponse) Reset() {
	*x = DeleteClassResponse{}
	mi := &file_proto_ace_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassResponse) ProtoMessage() {}

func (x *DeleteClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassResponse.ProtoReflect.Descriptor instead.
func (*DeleteClassResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteClassResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteClassResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WeekTopics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    int32                  `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeekTopics) Reset() {
	*x = WeekTopics{}
	mi := &file_proto_ace_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeekTopics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeekTopics) ProtoMessage() {}

func (x *WeekTopics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeekTopics.ProtoReflect.Descriptor instead.
func (*WeekTopics) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{24}
}

func (x *WeekTopics) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *WeekTopics) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetSyllabusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyllabusRequest) Reset() {
	*x = GetSyllabusRequest{}
	mi := &file_proto_ace_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyllabusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyllabusRequest) ProtoMessage() {}

func (x *GetSyllabusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyllabusRequest.ProtoReflect.Descriptor instead.
func (*GetSyllabusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{25}
}

func (x *GetSyllabusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSyllabusRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type GetSyllabusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weeks         []*WeekTopics          `protobuf:"bytes,1,rep,name=weeks,proto3" json:"weeks,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyllabusResponse) Reset() {
	*x = GetSyllabusResponse{}
	mi := &file_proto_ace_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyllabusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyllabusResponse) ProtoMessage() {}

func (x *GetSyllabusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyllabusResponse.ProtoReflect.Descriptor instead.
func (*GetSyllabusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{26}
}

func (x *GetSyllabusResponse) GetWeeks() []*WeekTopics {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *GetSyllabusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSyllabusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EditSyllabusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Weeks         []*WeekTopics          `protobuf:"bytes,3,rep,name=weeks,proto3" json:"weeks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditSyllabusRequest) Reset() {
	*x = EditSyllabusRequest{}
	mi := &file_proto_ace_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSyllabusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSyllabusRequest) ProtoMessage() {}

func (x *EditSyllabusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSyllabusRequest.ProtoReflect.Descriptor instead.
func (*EditSyllabusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{27}
}

func (x *EditSyllabusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EditSyllabusRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *EditSyllabusRequest) GetWeeks() []*WeekTopics {
	if x != nil {
		return x.Weeks
	}
	return nil
}

type EditSyllabusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditSyllabusResponse) Reset() {
	*x = EditSyllabusResponse{}
	mi := &file_proto_ace_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSyllabusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSyllabusResponse) ProtoMessage() {}

func (x *EditSyllabusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSyllabusResponse.ProtoReflect.Descriptor instead.
func (*EditSyllabusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{28}
}

func (x *EditSyllabusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EditSyllabusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ace_proto protoreflect.FileDescriptor

const file_proto_ace_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ace.proto\x12\x03ace\"\x9e\x01\n" +
	"\x0fSyllabusRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x04 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x05 \x01(\tR\tclassName\"\x8a\x01\n" +
	"\x10SyllabusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rnodes_created\x18\x03 \x01(\x05R\fnodesCreated\x12\x1d\n" +
	"\n" +
	"graph_json\x18\x04 \x01(\tR\tgraphJson\"z\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x04 \x01(\tR\aclassId\"*\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"|\n" +
	"\x11QuizResultRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x19\n" +
	"\bclass_id\x18\x04 \x01(\tR\aclassId\"H\n" +
	"\x12QuizResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x13AdaptiveQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rsyllabus_name\x18\x02 \x01(\tR\fsyllabusName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\"3\n" +
	"\x14AdaptiveQuizResponse\x12\x1b\n" +
	"\tquiz_json\x18\x01 \x01(\tR\bquizJson\"J\n" +
	"\x14GetQuizScoresRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\"\x98\x01\n" +
	"\x0fQuizScoreRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bclass_id\x18\x05 \x01(\tR\aclassId\"y\n" +
	"\x15GetQuizScoresResponse\x12,\n" +
	"\x06scores\x18\x01 \x03(\v2\x14.ace.QuizScoreRecordR\x06scores\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf7\x01\n" +
	"\rIngestRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\x05R\n" +
	"weekNumber\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x19\n" +
	"\braw_text\x18\x03 \x01(\tR\arawText\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x05 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tR\tclassName\x12\x1b\n" +
	"\tfile_data\x18\a \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\b \x01(\tR\bfileName\"D\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfb\x01\n" +
	"\vQuizRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\x05R\n" +
	"weekNumber\x12%\n" +
	"\x0equestion_count\x18\x02 \x01(\x05R\rquestionCount\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"regenerate\x18\x04 \x01(\bR\n" +
	"regenerate\x12/\n" +
	"\x13regeneration_prompt\x18\x05 \x01(\tR\x12regenerationPrompt\x12\x1f\n" +
	"\vweak_topics\x18\x06 \x03(\tR\n" +
	"weakTopics\x12\x19\n" +
	"\bclass_id\x18\a \x01(\tR\aclassId\"\x8b\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rquestion_text\x18\x02 \x01(\tR\fquestionText\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x120\n" +
	"\x14correct_option_index\x18\x04 \x01(\x05R\x12correctOptionIndex\";\n" +
	"\fQuizResponse\x12+\n" +
	"\tquestions\x18\x01 \x03(\v2\r.ace.QuestionR\tquestions\"\x9c\x01\n" +
	"\vCramRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_week\x18\x02 \x01(\x05R\tstartWeek\x12\x19\n" +
	"\bend_week\x18\x03 \x01(\x05R\aendWeek\x12\x1f\n" +
	"\vweak_topics\x18\x04 \x03(\tR\n" +
	"weakTopics\x12\x19\n" +
	"\bclass_id\x18\x05 \x01(\tR\aclassId\"y\n" +
	"\fCramResponse\x122\n" +
	"\x15dense_review_markdown\x18\x01 \x01(\tR\x13denseReviewMarkdown\x125\n" +
	"\x0frapid_fire_quiz\x18\x02 \x03(\v2\r.ace.QuestionR\rrapidFireQuiz\"\xd6\x01\n" +
	"\rLessonRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\x05R\n" +
	"weekNumber\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vweak_topics\x18\x03 \x03(\tR\n" +
	"weakTopics\x12\x1e\n" +
	"\n" +
	"regenerate\x18\x04 \x01(\bR\n" +
	"regenerate\x12/\n" +
	"\x13regeneration_prompt\x18\x05 \x01(\tR\x12regenerationPrompt\x12\x19\n" +
	"\bclass_id\x18\x06 \x01(\tR\aclassId\"\x9d\x01\n" +
	"\x0eLessonResponse\x12'\n" +
	"\x0flesson_markdown\x18\x01 \x01(\tR\x0elessonMarkdown\x12+\n" +
	"\texercises\x18\x02 \x03(\v2\r.ace.QuestionR\texercises\x125\n" +
	"\x16insufficient_materials\x18\x03 \x01(\bR\x15insufficientMaterials\"i\n" +
	"\x12SufficiencyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12\x1f\n" +
	"\vweek_number\x18\x03 \x01(\x05R\n" +
	"weekNumber\"\x9c\x01\n" +
	"\x13SufficiencyResponse\x125\n" +
	"\x16insufficient_materials\x18\x01 \x01(\bR\x15insufficientMaterials\x12/\n" +
	"\x13insufficient_topics\x18\x02 \x03(\tR\x12insufficientTopics\x12\x1d\n" +
	"\n" +
	"all_topics\x18\x03 \x03(\tR\tallTopics\"H\n" +
	"\x12DeleteClassRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\"I\n" +
	"\x13DeleteClassResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\n" +
	"WeekTopics\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\x05R\n" +
	"weekNumber\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"H\n" +
	"\x12GetSyllabusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\"p\n" +
	"\x13GetSyllabusResponse\x12%\n" +
	"\x05weeks\x18\x01 \x03(\v2\x0f.ace.WeekTopicsR\x05weeks\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"p\n" +
	"\x13EditSyllabusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12%\n" +
	"\x05weeks\x18\x03 \x03(\v2\x0f.ace.WeekTopicsR\x05weeks\"J\n" +
	"\x14EditSyllabusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x98\a\n" +
	"\fTutorService\x12>\n" +
	"\x0fProcessSyllabus\x12\x14.ace.SyllabusRequest\x1a\x15.ace.SyllabusResponse\x12+\n" +
	"\x04Chat\x12\x10.ace.ChatRequest\x1a\x11.ace.ChatResponse\x12C\n" +
	"\x10SubmitQuizResult\x12\x16.ace.QuizResultRequest\x1a\x17.ace.QuizResultResponse\x12K\n" +
	"\x14GenerateAdaptiveQuiz\x12\x18.ace.AdaptiveQuizRequest\x1a\x19.ace.AdaptiveQuizResponse\x12F\n" +
	"\rGetQuizScores\x12\x19.ace.GetQuizScoresRequest\x1a\x1a.ace.GetQuizScoresResponse\x129\n" +
	"\x0eIngestMaterial\x12\x12.ace.IngestRequest\x1a\x13.ace.IngestResponse\x123\n" +
	"\fGenerateQuiz\x12\x10.ace.QuizRequest\x1a\x11.ace.QuizResponse\x12:\n" +
	"\x13GenerateCramSession\x12\x10.ace.CramRequest\x1a\x11.ace.CramResponse\x129\n" +
	"\x0eGenerateLesson\x12\x12.ace.LessonRequest\x1a\x13.ace.LessonResponse\x12E\n" +
	"\x1aGenerateLessonAndExercises\x12\x12.ace.LessonRequest\x1a\x13.ace.LessonResponse\x12J\n" +
	"\x15CheckTopicSufficiency\x12\x17.ace.SufficiencyRequest\x1a\x18.ace.SufficiencyResponse\x12@\n" +
	"\vDeleteClass\x12\x17.ace.DeleteClassRequest\x1a\x18.ace.DeleteClassResponse\x12@\n" +
	"\vGetSyllabus\x12\x17.ace.GetSyllabusRequest\x1a\x18.ace.GetSyllabusResponse\x12C\n" +
	"\fEditSyllabus\x12\x18.ace.EditSyllabusRequest\x1a\x19.ace.EditSyllabusResponseB\x1cZ\x1aace-agent/backend-go/protob\x06proto3"

var (
	file_proto_ace_proto_rawDescOnce sync.Once
	file_proto_ace_proto_rawDescData []byte
)

func file_proto_ace_proto_rawDescGZIP() []byte {
	file_proto_ace_proto_rawDescOnce.Do(func() {
		file_proto_ace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ace_proto_rawDesc), len(file_proto_ace_proto_rawDesc)))
	})
	return file_proto_ace_proto_rawDescData
}

var file_proto_ace_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_ace_proto_goTypes = []any{
	(*SyllabusRequest)(nil),       // 0: ace.SyllabusRequest
	(*SyllabusResponse)(nil),      // 1: ace.SyllabusResponse
	(*ChatRequest)(nil),           // 2: ace.ChatRequest
	(*ChatResponse)(nil),          // 3: ace.ChatResponse
	(*QuizResultRequest)(nil),     // 4: ace.QuizResultRequest
	(*QuizResultResponse)(nil),    // 5: ace.QuizResultResponse
	(*AdaptiveQuizRequest)(nil),   // 6: ace.AdaptiveQuizRequest
	(*AdaptiveQuizResponse)(nil),  // 7: ace.AdaptiveQuizResponse
	(*GetQuizScoresRequest)(nil),  // 8: ace.GetQuizScoresRequest
	(*QuizScoreRecord)(nil),       // 9: ace.QuizScoreRecord
	(*GetQuizScoresResponse)(nil), // 10: ace.GetQuizScoresResponse
	(*IngestRequest)(nil),         // 11: ace.IngestRequest
	(*IngestResponse)(nil),        // 12: ace.IngestResponse
	(*QuizRequest)(nil),           // 13: ace.QuizRequest
	(*Question)(nil),              // 14: ace.Question
	(*QuizResponse)(nil),          // 15: ace.QuizResponse
	(*CramRequest)(nil),           // 16: ace.CramRequest
	(*CramResponse)(nil),          // 17: ace.CramResponse
	(*LessonRequest)(nil),         // 18: ace.LessonRequest
	(*LessonResponse)(nil),        // 19: ace.LessonResponse
	(*SufficiencyRequest)(nil),    // 20: ace.SufficiencyRequest
	(*SufficiencyResponse)(nil),   // 21: ace.SufficiencyResponse
	(*DeleteClassRequest)(nil),    // 22: ace.DeleteClassRequest
	(*DeleteClassResponse)(nil),   // 23: ace.DeleteClassResponse
	(*WeekTopics)(nil),            // 24: ace.WeekTopics
	(*GetSyllabusRequest)(nil),    // 25: ace.GetSyllabusRequest
	(*GetSyllabusResponse)(nil),   // 26: ace.GetSyllabusResponse
	(*EditSyllabusRequest)(nil),   // 27: ace.EditSyllabusRequest
	(*EditSyllabusResponse)(nil),  // 28: ace.EditSyllabusResponse
}
var file_proto_ace_proto_depIdxs = []int32{
	9,  // 0: ace.GetQuizScoresResponse.scores:type_name -> ace.QuizScoreRecord
	14, // 1: ace.QuizResponse.questions:type_name -> ace.Question
	14, // 2: ace.CramResponse.rapid_fire_quiz:type_name -> ace.Question
	14, // 3: ace.LessonResponse.exercises:type_name -> ace.Question
	24, // 4: ace.GetSyllabusResponse.weeks:type_name -> ace.WeekTopics
	24, // 5: ace.EditSyllabusRequest.weeks:type_name -> ace.WeekTopics
	0,  // 6: ace.TutorService.ProcessSyllabus:input_type -> ace.SyllabusRequest
	2,  // 7: ace.TutorService.Chat:input_type -> ace.ChatRequest
	4,  // 8: ace.TutorService.SubmitQuizResult:input_type -> ace.QuizResultRequest
	6,  // 9: ace.TutorService.GenerateAdaptiveQuiz:input_type -> ace.AdaptiveQuizRequest
	8,  // 10: ace.TutorService.GetQuizScores:input_type -> ace.GetQuizScoresRequest
	11, // 11: ace.TutorService.IngestMaterial:input_type -> ace.IngestRequest
	13, // 12: ace.TutorService.GenerateQuiz:input_type -> ace.QuizRequest
	16, // 13: ace.TutorService.GenerateCramSession:input_type -> ace.CramRequest
	18, // 14: ace.TutorService.GenerateLesson:input_type -> ace.LessonRequest
	18, // 15: ace.TutorService.GenerateLessonAndExercises:input_type -> ace.LessonRequest
	20, // 16: ace.TutorService.CheckTopicSufficiency:input_type -> ace.SufficiencyRequest
	22, // 17: ace.TutorService.DeleteClass:input_type -> ace.DeleteClassRequest
	25, // 18: ace.TutorService.GetSyllabus:input_type -> ace.GetSyllabusRequest
	27, // 19: ace.TutorService.EditSyllabus:input_type -> ace.EditSyllabusRequest
	1,  // 20: ace.TutorService.ProcessSyllabus:output_type -> ace.SyllabusResponse
	3,  // 21: ace.TutorService.Chat:output_type -> ace.ChatResponse
	5,  // 22: ace.TutorService.SubmitQuizResult:output_type -> ace.QuizResultResponse
	7,  // 23: ace.TutorService.GenerateAdaptiveQuiz:output_type -> ace.AdaptiveQuizResponse
	10, // 24: ace.TutorService.GetQuizScores:output_type -> ace.GetQuizScoresResponse
	12, // 25: ace.TutorService.IngestMaterial:output_type -> ace.IngestResponse
	15, // 26: ace.TutorService.GenerateQuiz:output_type -> ace.QuizResponse
	17, // 27: ace.TutorService.GenerateCramSession:output_type -> ace.CramResponse
	19, // 28: ace.TutorService.GenerateLesson:output_type -> ace.LessonResponse
	19, // 29: ace.TutorService.GenerateLessonAndExercises:output_type -> ace.LessonResponse
	21, // 30: ace.TutorService.CheckTopicSufficiency:output_type -> ace.SufficiencyResponse
	23, // 31: ace.TutorService.DeleteClass:output_type -> ace.DeleteClassResponse
	26, // 32: ace.TutorService.GetSyllabus:output_type -> ace.GetSyllabusResponse
	28, // 33: ace.TutorService.EditSyllabus:output_type -> ace.EditSyllabusResponse
	20, // [20:34] is the sub-list for method output_type
	6,  // [6:20] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_ace_proto_init() }
func file_proto_ace_proto_init() {
	if File_proto_ace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ace_proto_rawDesc), len(file_proto_ace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ace_proto_goTypes,
		DependencyIndexes: file_proto_ace_proto_depIdxs,
		MessageInfos:      file_proto_ace_proto_msgTypes,
	}.Build()
	File_proto_ace_proto = out.File
	file_proto_ace_proto_goTypes = nil
	file_proto_ace_proto_depIdxs = nil
}
