// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/ace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyllabusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusRequest) Reset() {
	*x = SyllabusRequest{}
	mi := &file_proto_ace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusRequest) ProtoMessage() {}

func (x *SyllabusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusRequest.ProtoReflect.Descriptor instead.
func (*SyllabusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{0}
}

func (x *SyllabusRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SyllabusRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type SyllabusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodesCreated  int32                  `protobuf:"varint,3,opt,name=nodes_created,json=nodesCreated,proto3" json:"nodes_created,omitempty"`
	GraphJson     string                 `protobuf:"bytes,4,opt,name=graph_json,json=graphJson,proto3" json:"graph_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusResponse) Reset() {
	*x = SyllabusResponse{}
	mi := &file_proto_ace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusResponse) ProtoMessage() {}

func (x *SyllabusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusResponse.ProtoReflect.Descriptor instead.
func (*SyllabusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{1}
}

func (x *SyllabusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyllabusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyllabusResponse) GetNodesCreated() int32 {
	if x != nil {
		return x.NodesCreated
	}
	return 0
}

func (x *SyllabusResponse) GetGraphJson() string {
	if x != nil {
		return x.GraphJson
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                      // The user's question
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // To track conversation history later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_ace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // The AI's answer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_ace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// Sent by UI when a student finishes a quiz
type QuizResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResultRequest) Reset() {
	*x = QuizResultRequest{}
	mi := &file_proto_ace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultRequest) ProtoMessage() {}

func (x *QuizResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultRequest.ProtoReflect.Descriptor instead.
func (*QuizResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{4}
}

func (x *QuizResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizResultRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *QuizResultRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type QuizResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResultResponse) Reset() {
	*x = QuizResultResponse{}
	mi := &file_proto_ace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultResponse) ProtoMessage() {}

func (x *QuizResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultResponse.ProtoReflect.Descriptor instead.
func (*QuizResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{5}
}

func (x *QuizResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QuizResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sent by UI when a student clicks "Generate Review Quiz"
type AdaptiveQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SyllabusName  string                 `protobuf:"bytes,2,opt,name=syllabus_name,json=syllabusName,proto3" json:"syllabus_name,omitempty"` // Which class are they studying for?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptiveQuizRequest) Reset() {
	*x = AdaptiveQuizRequest{}
	mi := &file_proto_ace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveQuizRequest) ProtoMessage() {}

func (x *AdaptiveQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveQuizRequest.ProtoReflect.Descriptor instead.
func (*AdaptiveQuizRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{6}
}

func (x *AdaptiveQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdaptiveQuizRequest) GetSyllabusName() string {
	if x != nil {
		return x.SyllabusName
	}
	return ""
}

// We can reuse ChatResponse for the quiz return, or make a specific one:
type AdaptiveQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizJson      string                 `protobuf:"bytes,1,opt,name=quiz_json,json=quizJson,proto3" json:"quiz_json,omitempty"` // Gemini's strict JSON output of questions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptiveQuizResponse) Reset() {
	*x = AdaptiveQuizResponse{}
	mi := &file_proto_ace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveQuizResponse) ProtoMessage() {}

func (x *AdaptiveQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveQuizResponse.ProtoReflect.Descriptor instead.
func (*AdaptiveQuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{7}
}

func (x *AdaptiveQuizResponse) GetQuizJson() string {
	if x != nil {
		return x.QuizJson
	}
	return ""
}

// Sent by UI to read student performance/scores
type GetQuizScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizScoresRequest) Reset() {
	*x = GetQuizScoresRequest{}
	mi := &file_proto_ace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizScoresRequest) ProtoMessage() {}

func (x *GetQuizScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizScoresRequest.ProtoReflect.Descriptor instead.
func (*GetQuizScoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{8}
}

func (x *GetQuizScoresRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QuizScoreRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizScoreRecord) Reset() {
	*x = QuizScoreRecord{}
	mi := &file_proto_ace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizScoreRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizScoreRecord) ProtoMessage() {}

func (x *QuizScoreRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizScoreRecord.ProtoReflect.Descriptor instead.
func (*QuizScoreRecord) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{9}
}

func (x *QuizScoreRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizScoreRecord) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *QuizScoreRecord) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizScoreRecord) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetQuizScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*QuizScoreRecord     `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizScoresResponse) Reset() {
	*x = GetQuizScoresResponse{}
	mi := &file_proto_ace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizScoresResponse) ProtoMessage() {}

func (x *GetQuizScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizScoresResponse.ProtoReflect.Descriptor instead.
func (*GetQuizScoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuizScoresResponse) GetScores() []*QuizScoreRecord {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *GetQuizScoresResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetQuizScoresResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    int32                  `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	RawText       string                 `protobuf:"bytes,3,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_ace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{11}
}

func (x *IngestRequest) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *IngestRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *IngestRequest) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *IngestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_ace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{12}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    int32                  `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	QuestionCount int32                  `protobuf:"varint,2,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WeakTopics    []string               `protobuf:"bytes,4,rep,name=weak_topics,json=weakTopics,proto3" json:"weak_topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizRequest) Reset() {
	*x = QuizRequest{}
	mi := &file_proto_ace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizRequest) ProtoMessage() {}

func (x *QuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizRequest.ProtoReflect.Descriptor instead.
func (*QuizRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{13}
}

func (x *QuizRequest) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *QuizRequest) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *QuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizRequest) GetWeakTopics() []string {
	if x != nil {
		return x.WeakTopics
	}
	return nil
}

type Question struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionText       string                 `protobuf:"bytes,2,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	Options            []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	CorrectOptionIndex int32                  `protobuf:"varint,4,opt,name=correct_option_index,json=correctOptionIndex,proto3" json:"correct_option_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_ace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{14}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetCorrectOptionIndex() int32 {
	if x != nil {
		return x.CorrectOptionIndex
	}
	return 0
}

type QuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResponse) Reset() {
	*x = QuizResponse{}
	mi := &file_proto_ace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResponse) ProtoMessage() {}

func (x *QuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResponse.ProtoReflect.Descriptor instead.
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{15}
}

func (x *QuizResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

var File_proto_ace_proto protoreflect.FileDescriptor

const file_proto_ace_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ace.proto\x12\x03ace\"K\n" +
	"\x0fSyllabusRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\"\x8a\x01\n" +
	"\x10SyllabusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rnodes_created\x18\x03 \x01(\x05R\fnodesCreated\x12\x1d\n" +
	"\n" +
	"graph_json\x18\x04 \x01(\tR\tgraphJson\"F\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"*\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"a\n" +
	"\x11QuizResultRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"H\n" +
	"\x12QuizResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x13AdaptiveQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rsyllabus_name\x18\x02 \x01(\tR\fsyllabusName\"3\n" +
	"\x14AdaptiveQuizResponse\x12\x1b\n" +
	"\tquiz_json\x18\x01 \x01(\tR\bquizJson\"/\n" +
	"\x14GetQuizScoresRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"}\n" +
	"\x0fQuizScoreRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"y\n" +
	"\x15GetQuizScoresResponse\x12,\n" +
	"\x06scores\x18\x01 \x03(\v2\x14.ace.QuizScoreRecordR\x06scores\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x83\x01\n" +
	"\rIngestRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\x05R\n" +
	"weekNumber\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x19\n" +
	"\braw_text\x18\x03 \x01(\tR\arawText\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"D\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8f\x01\n" +
	"\vQuizRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\x05R\n" +
	"weekNumber\x12%\n" +
	"\x0equestion_count\x18\x02 \x01(\x05R\rquestionCount\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vweak_topics\x18\x04 \x03(\tR\n" +
	"weakTopics\"\x8b\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rquestion_text\x18\x02 \x01(\tR\fquestionText\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x120\n" +
	"\x14correct_option_index\x18\x04 \x01(\x05R\x12correctOptionIndex\";\n" +
	"\fQuizResponse\x12+\n" +
	"\tquestions\x18\x01 \x03(\v2\r.ace.QuestionR\tquestions2\xc5\x03\n" +
	"\fTutorService\x12>\n" +
	"\x0fProcessSyllabus\x12\x14.ace.SyllabusRequest\x1a\x15.ace.SyllabusResponse\x12+\n" +
	"\x04Chat\x12\x10.ace.ChatRequest\x1a\x11.ace.ChatResponse\x12C\n" +
	"\x10SubmitQuizResult\x12\x16.ace.QuizResultRequest\x1a\x17.ace.QuizResultResponse\x12K\n" +
	"\x14GenerateAdaptiveQuiz\x12\x18.ace.AdaptiveQuizRequest\x1a\x19.ace.AdaptiveQuizResponse\x12F\n" +
	"\rGetQuizScores\x12\x19.ace.GetQuizScoresRequest\x1a\x1a.ace.GetQuizScoresResponse\x129\n" +
	"\x0eIngestMaterial\x12\x12.ace.IngestRequest\x1a\x13.ace.IngestResponse\x123\n" +
	"\fGenerateQuiz\x12\x10.ace.QuizRequest\x1a\x11.ace.QuizResponseB\x1cZ\x1aace-agent/backend-go/protob\x06proto3"

var (
	file_proto_ace_proto_rawDescOnce sync.Once
	file_proto_ace_proto_rawDescData []byte
)

func file_proto_ace_proto_rawDescGZIP() []byte {
	file_proto_ace_proto_rawDescOnce.Do(func() {
		file_proto_ace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ace_proto_rawDesc), len(file_proto_ace_proto_rawDesc)))
	})
	return file_proto_ace_proto_rawDescData
}

var file_proto_ace_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_ace_proto_goTypes = []any{
	(*SyllabusRequest)(nil),       // 0: ace.SyllabusRequest
	(*SyllabusResponse)(nil),      // 1: ace.SyllabusResponse
	(*ChatRequest)(nil),           // 2: ace.ChatRequest
	(*ChatResponse)(nil),          // 3: ace.ChatResponse
	(*QuizResultRequest)(nil),     // 4: ace.QuizResultRequest
	(*QuizResultResponse)(nil),    // 5: ace.QuizResultResponse
	(*AdaptiveQuizRequest)(nil),   // 6: ace.AdaptiveQuizRequest
	(*AdaptiveQuizResponse)(nil),  // 7: ace.AdaptiveQuizResponse
	(*GetQuizScoresRequest)(nil),  // 8: ace.GetQuizScoresRequest
	(*QuizScoreRecord)(nil),       // 9: ace.QuizScoreRecord
	(*GetQuizScoresResponse)(nil), // 10: ace.GetQuizScoresResponse
	(*IngestRequest)(nil),         // 11: ace.IngestRequest
	(*IngestResponse)(nil),        // 12: ace.IngestResponse
	(*QuizRequest)(nil),           // 13: ace.QuizRequest
	(*Question)(nil),              // 14: ace.Question
	(*QuizResponse)(nil),          // 15: ace.QuizResponse
}
var file_proto_ace_proto_depIdxs = []int32{
	9,  // 0: ace.GetQuizScoresResponse.scores:type_name -> ace.QuizScoreRecord
	14, // 1: ace.QuizResponse.questions:type_name -> ace.Question
	0,  // 2: ace.TutorService.ProcessSyllabus:input_type -> ace.SyllabusRequest
	2,  // 3: ace.TutorService.Chat:input_type -> ace.ChatRequest
	4,  // 4: ace.TutorService.SubmitQuizResult:input_type -> ace.QuizResultRequest
	6,  // 5: ace.TutorService.GenerateAdaptiveQuiz:input_type -> ace.AdaptiveQuizRequest
	8,  // 6: ace.TutorService.GetQuizScores:input_type -> ace.GetQuizScoresRequest
	11, // 7: ace.TutorService.IngestMaterial:input_type -> ace.IngestRequest
	13, // 8: ace.TutorService.GenerateQuiz:input_type -> ace.QuizRequest
	1,  // 9: ace.TutorService.ProcessSyllabus:output_type -> ace.SyllabusResponse
	3,  // 10: ace.TutorService.Chat:output_type -> ace.ChatResponse
	5,  // 11: ace.TutorService.SubmitQuizResult:output_type -> ace.QuizResultResponse
	7,  // 12: ace.TutorService.GenerateAdaptiveQuiz:output_type -> ace.AdaptiveQuizResponse
	10, // 13: ace.TutorService.GetQuizScores:output_type -> ace.GetQuizScoresResponse
	12, // 14: ace.TutorService.IngestMaterial:output_type -> ace.IngestResponse
	15, // 15: ace.TutorService.GenerateQuiz:output_type -> ace.QuizResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ace_proto_init() }
func file_proto_ace_proto_init() {
	if File_proto_ace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ace_proto_rawDesc), len(file_proto_ace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ace_proto_goTypes,
		DependencyIndexes: file_proto_ace_proto_depIdxs,
		MessageInfos:      file_proto_ace_proto_msgTypes,
	}.Build()
	File_proto_ace_proto = out.File
	file_proto_ace_proto_goTypes = nil
	file_proto_ace_proto_depIdxs = nil
}
