// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: ace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyllabusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"` // NEW: The actual PDF bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusRequest) Reset() {
	*x = SyllabusRequest{}
	mi := &file_ace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusRequest) ProtoMessage() {}

func (x *SyllabusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusRequest.ProtoReflect.Descriptor instead.
func (*SyllabusRequest) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{0}
}

func (x *SyllabusRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SyllabusRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type SyllabusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodesCreated  int32                  `protobuf:"varint,3,opt,name=nodes_created,json=nodesCreated,proto3" json:"nodes_created,omitempty"`
	GraphJson     string                 `protobuf:"bytes,4,opt,name=graph_json,json=graphJson,proto3" json:"graph_json,omitempty"` // NEW: The node data for the UI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusResponse) Reset() {
	*x = SyllabusResponse{}
	mi := &file_ace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusResponse) ProtoMessage() {}

func (x *SyllabusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusResponse.ProtoReflect.Descriptor instead.
func (*SyllabusResponse) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{1}
}

func (x *SyllabusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyllabusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyllabusResponse) GetNodesCreated() int32 {
	if x != nil {
		return x.NodesCreated
	}
	return 0
}

func (x *SyllabusResponse) GetGraphJson() string {
	if x != nil {
		return x.GraphJson
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                      // The user's question
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // To track conversation history later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // The AI's answer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// Sent by UI when a student finishes a quiz
type QuizResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResultRequest) Reset() {
	*x = QuizResultRequest{}
	mi := &file_ace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultRequest) ProtoMessage() {}

func (x *QuizResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultRequest.ProtoReflect.Descriptor instead.
func (*QuizResultRequest) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{4}
}

func (x *QuizResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuizResultRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *QuizResultRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type QuizResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizResultResponse) Reset() {
	*x = QuizResultResponse{}
	mi := &file_ace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResultResponse) ProtoMessage() {}

func (x *QuizResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResultResponse.ProtoReflect.Descriptor instead.
func (*QuizResultResponse) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{5}
}

func (x *QuizResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QuizResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sent by UI when a student clicks "Generate Review Quiz"
type AdaptiveQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SyllabusName  string                 `protobuf:"bytes,2,opt,name=syllabus_name,json=syllabusName,proto3" json:"syllabus_name,omitempty"` // Which class are they studying for?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptiveQuizRequest) Reset() {
	*x = AdaptiveQuizRequest{}
	mi := &file_ace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveQuizRequest) ProtoMessage() {}

func (x *AdaptiveQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveQuizRequest.ProtoReflect.Descriptor instead.
func (*AdaptiveQuizRequest) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{6}
}

func (x *AdaptiveQuizRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdaptiveQuizRequest) GetSyllabusName() string {
	if x != nil {
		return x.SyllabusName
	}
	return ""
}

// We can reuse ChatResponse for the quiz return, or make a specific one:
type AdaptiveQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizJson      string                 `protobuf:"bytes,1,opt,name=quiz_json,json=quizJson,proto3" json:"quiz_json,omitempty"` // Gemini's strict JSON output of questions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptiveQuizResponse) Reset() {
	*x = AdaptiveQuizResponse{}
	mi := &file_ace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveQuizResponse) ProtoMessage() {}

func (x *AdaptiveQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveQuizResponse.ProtoReflect.Descriptor instead.
func (*AdaptiveQuizResponse) Descriptor() ([]byte, []int) {
	return file_ace_proto_rawDescGZIP(), []int{7}
}

func (x *AdaptiveQuizResponse) GetQuizJson() string {
	if x != nil {
		return x.QuizJson
	}
	return ""
}

var File_ace_proto protoreflect.FileDescriptor

const file_ace_proto_rawDesc = "" +
	"\n" +
	"\tace.proto\x12\x03ace\"K\n" +
	"\x0fSyllabusRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\"\x8a\x01\n" +
	"\x10SyllabusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rnodes_created\x18\x03 \x01(\x05R\fnodesCreated\x12\x1d\n" +
	"\n" +
	"graph_json\x18\x04 \x01(\tR\tgraphJson\"F\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"*\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"a\n" +
	"\x11QuizResultRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"H\n" +
	"\x12QuizResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x13AdaptiveQuizRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rsyllabus_name\x18\x02 \x01(\tR\fsyllabusName\"3\n" +
	"\x14AdaptiveQuizResponse\x12\x1b\n" +
	"\tquiz_json\x18\x01 \x01(\tR\bquizJson2\x8d\x02\n" +
	"\fTutorService\x12>\n" +
	"\x0fProcessSyllabus\x12\x14.ace.SyllabusRequest\x1a\x15.ace.SyllabusResponse\x12+\n" +
	"\x04Chat\x12\x10.ace.ChatRequest\x1a\x11.ace.ChatResponse\x12C\n" +
	"\x10SubmitQuizResult\x12\x16.ace.QuizResultRequest\x1a\x17.ace.QuizResultResponse\x12K\n" +
	"\x14GenerateAdaptiveQuiz\x12\x18.ace.AdaptiveQuizRequest\x1a\x19.ace.AdaptiveQuizResponseB\n" +
	"Z\bpb/protob\x06proto3"

var (
	file_ace_proto_rawDescOnce sync.Once
	file_ace_proto_rawDescData []byte
)

func file_ace_proto_rawDescGZIP() []byte {
	file_ace_proto_rawDescOnce.Do(func() {
		file_ace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ace_proto_rawDesc), len(file_ace_proto_rawDesc)))
	})
	return file_ace_proto_rawDescData
}

var file_ace_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ace_proto_goTypes = []any{
	(*SyllabusRequest)(nil),      // 0: ace.SyllabusRequest
	(*SyllabusResponse)(nil),     // 1: ace.SyllabusResponse
	(*ChatRequest)(nil),          // 2: ace.ChatRequest
	(*ChatResponse)(nil),         // 3: ace.ChatResponse
	(*QuizResultRequest)(nil),    // 4: ace.QuizResultRequest
	(*QuizResultResponse)(nil),   // 5: ace.QuizResultResponse
	(*AdaptiveQuizRequest)(nil),  // 6: ace.AdaptiveQuizRequest
	(*AdaptiveQuizResponse)(nil), // 7: ace.AdaptiveQuizResponse
}
var file_ace_proto_depIdxs = []int32{
	0, // 0: ace.TutorService.ProcessSyllabus:input_type -> ace.SyllabusRequest
	2, // 1: ace.TutorService.Chat:input_type -> ace.ChatRequest
	4, // 2: ace.TutorService.SubmitQuizResult:input_type -> ace.QuizResultRequest
	6, // 3: ace.TutorService.GenerateAdaptiveQuiz:input_type -> ace.AdaptiveQuizRequest
	1, // 4: ace.TutorService.ProcessSyllabus:output_type -> ace.SyllabusResponse
	3, // 5: ace.TutorService.Chat:output_type -> ace.ChatResponse
	5, // 6: ace.TutorService.SubmitQuizResult:output_type -> ace.QuizResultResponse
	7, // 7: ace.TutorService.GenerateAdaptiveQuiz:output_type -> ace.AdaptiveQuizResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ace_proto_init() }
func file_ace_proto_init() {
	if File_ace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ace_proto_rawDesc), len(file_ace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ace_proto_goTypes,
		DependencyIndexes: file_ace_proto_depIdxs,
		MessageInfos:      file_ace_proto_msgTypes,
	}.Build()
	File_ace_proto = out.File
	file_ace_proto_goTypes = nil
	file_ace_proto_depIdxs = nil
}
