// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/ace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyllabusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"` // NEW: The actual PDF bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusRequest) Reset() {
	*x = SyllabusRequest{}
	mi := &file_proto_ace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusRequest) ProtoMessage() {}

func (x *SyllabusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusRequest.ProtoReflect.Descriptor instead.
func (*SyllabusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{0}
}

func (x *SyllabusRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SyllabusRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type SyllabusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodesCreated  int32                  `protobuf:"varint,3,opt,name=nodes_created,json=nodesCreated,proto3" json:"nodes_created,omitempty"`
	GraphJson     string                 `protobuf:"bytes,4,opt,name=graph_json,json=graphJson,proto3" json:"graph_json,omitempty"` // NEW: The node data for the UI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyllabusResponse) Reset() {
	*x = SyllabusResponse{}
	mi := &file_proto_ace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyllabusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyllabusResponse) ProtoMessage() {}

func (x *SyllabusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyllabusResponse.ProtoReflect.Descriptor instead.
func (*SyllabusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{1}
}

func (x *SyllabusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyllabusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyllabusResponse) GetNodesCreated() int32 {
	if x != nil {
		return x.NodesCreated
	}
	return 0
}

func (x *SyllabusResponse) GetGraphJson() string {
	if x != nil {
		return x.GraphJson
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                      // The user's question
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // To track conversation history later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_ace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // The AI's answer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_ace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_ace_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_ace_proto protoreflect.FileDescriptor

const file_proto_ace_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ace.proto\x12\x03ace\"K\n" +
	"\x0fSyllabusRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\"\x8a\x01\n" +
	"\x10SyllabusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rnodes_created\x18\x03 \x01(\x05R\fnodesCreated\x12\x1d\n" +
	"\n" +
	"graph_json\x18\x04 \x01(\tR\tgraphJson\"F\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"*\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2{\n" +
	"\fTutorService\x12>\n" +
	"\x0fProcessSyllabus\x12\x14.ace.SyllabusRequest\x1a\x15.ace.SyllabusResponse\x12+\n" +
	"\x04Chat\x12\x10.ace.ChatRequest\x1a\x11.ace.ChatResponseB\n" +
	"Z\bpb/protob\x06proto3"

var (
	file_proto_ace_proto_rawDescOnce sync.Once
	file_proto_ace_proto_rawDescData []byte
)

func file_proto_ace_proto_rawDescGZIP() []byte {
	file_proto_ace_proto_rawDescOnce.Do(func() {
		file_proto_ace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ace_proto_rawDesc), len(file_proto_ace_proto_rawDesc)))
	})
	return file_proto_ace_proto_rawDescData
}

var file_proto_ace_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ace_proto_goTypes = []any{
	(*SyllabusRequest)(nil),  // 0: ace.SyllabusRequest
	(*SyllabusResponse)(nil), // 1: ace.SyllabusResponse
	(*ChatRequest)(nil),      // 2: ace.ChatRequest
	(*ChatResponse)(nil),     // 3: ace.ChatResponse
}
var file_proto_ace_proto_depIdxs = []int32{
	0, // 0: ace.TutorService.ProcessSyllabus:input_type -> ace.SyllabusRequest
	2, // 1: ace.TutorService.Chat:input_type -> ace.ChatRequest
	1, // 2: ace.TutorService.ProcessSyllabus:output_type -> ace.SyllabusResponse
	3, // 3: ace.TutorService.Chat:output_type -> ace.ChatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ace_proto_init() }
func file_proto_ace_proto_init() {
	if File_proto_ace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ace_proto_rawDesc), len(file_proto_ace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ace_proto_goTypes,
		DependencyIndexes: file_proto_ace_proto_depIdxs,
		MessageInfos:      file_proto_ace_proto_msgTypes,
	}.Build()
	File_proto_ace_proto = out.File
	file_proto_ace_proto_goTypes = nil
	file_proto_ace_proto_depIdxs = nil
}
