// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: ace.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TutorService_ProcessSyllabus_FullMethodName            = "/ace.TutorService/ProcessSyllabus"
	TutorService_Chat_FullMethodName                       = "/ace.TutorService/Chat"
	TutorService_SubmitQuizResult_FullMethodName           = "/ace.TutorService/SubmitQuizResult"
	TutorService_GenerateAdaptiveQuiz_FullMethodName       = "/ace.TutorService/GenerateAdaptiveQuiz"
	TutorService_GetQuizScores_FullMethodName              = "/ace.TutorService/GetQuizScores"
	TutorService_IngestMaterial_FullMethodName             = "/ace.TutorService/IngestMaterial"
	TutorService_GenerateQuiz_FullMethodName               = "/ace.TutorService/GenerateQuiz"
	TutorService_GenerateCramSession_FullMethodName        = "/ace.TutorService/GenerateCramSession"
	TutorService_GenerateLesson_FullMethodName             = "/ace.TutorService/GenerateLesson"
	TutorService_GenerateLessonAndExercises_FullMethodName = "/ace.TutorService/GenerateLessonAndExercises"
	TutorService_CheckTopicSufficiency_FullMethodName      = "/ace.TutorService/CheckTopicSufficiency"
	TutorService_DeleteClass_FullMethodName                = "/ace.TutorService/DeleteClass"
	TutorService_GetSyllabus_FullMethodName                = "/ace.TutorService/GetSyllabus"
	TutorService_EditSyllabus_FullMethodName               = "/ace.TutorService/EditSyllabus"
)

// TutorServiceClient is the client API for TutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TutorServiceClient interface {
	ProcessSyllabus(ctx context.Context, in *SyllabusRequest, opts ...grpc.CallOption) (*SyllabusResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	SubmitQuizResult(ctx context.Context, in *QuizResultRequest, opts ...grpc.CallOption) (*QuizResultResponse, error)
	GenerateAdaptiveQuiz(ctx context.Context, in *AdaptiveQuizRequest, opts ...grpc.CallOption) (*AdaptiveQuizResponse, error)
	GetQuizScores(ctx context.Context, in *GetQuizScoresRequest, opts ...grpc.CallOption) (*GetQuizScoresResponse, error)
	IngestMaterial(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	GenerateQuiz(ctx context.Context, in *QuizRequest, opts ...grpc.CallOption) (*QuizResponse, error)
	GenerateCramSession(ctx context.Context, in *CramRequest, opts ...grpc.CallOption) (*CramResponse, error)
	GenerateLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonResponse, error)
	GenerateLessonAndExercises(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonResponse, error)
	CheckTopicSufficiency(ctx context.Context, in *SufficiencyRequest, opts ...grpc.CallOption) (*SufficiencyResponse, error)
	DeleteClass(ctx context.Context, in *DeleteClassRequest, opts ...grpc.CallOption) (*DeleteClassResponse, error)
	GetSyllabus(ctx context.Context, in *GetSyllabusRequest, opts ...grpc.CallOption) (*GetSyllabusResponse, error)
	EditSyllabus(ctx context.Context, in *EditSyllabusRequest, opts ...grpc.CallOption) (*EditSyllabusResponse, error)
}

type tutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTutorServiceClient(cc grpc.ClientConnInterface) TutorServiceClient {
	return &tutorServiceClient{cc}
}

func (c *tutorServiceClient) ProcessSyllabus(ctx context.Context, in *SyllabusRequest, opts ...grpc.CallOption) (*SyllabusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyllabusResponse)
	err := c.cc.Invoke(ctx, TutorService_ProcessSyllabus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, TutorService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) SubmitQuizResult(ctx context.Context, in *QuizResultRequest, opts ...grpc.CallOption) (*QuizResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuizResultResponse)
	err := c.cc.Invoke(ctx, TutorService_SubmitQuizResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GenerateAdaptiveQuiz(ctx context.Context, in *AdaptiveQuizRequest, opts ...grpc.CallOption) (*AdaptiveQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdaptiveQuizResponse)
	err := c.cc.Invoke(ctx, TutorService_GenerateAdaptiveQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GetQuizScores(ctx context.Context, in *GetQuizScoresRequest, opts ...grpc.CallOption) (*GetQuizScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuizScoresResponse)
	err := c.cc.Invoke(ctx, TutorService_GetQuizScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) IngestMaterial(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, TutorService_IngestMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GenerateQuiz(ctx context.Context, in *QuizRequest, opts ...grpc.CallOption) (*QuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuizResponse)
	err := c.cc.Invoke(ctx, TutorService_GenerateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GenerateCramSession(ctx context.Context, in *CramRequest, opts ...grpc.CallOption) (*CramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CramResponse)
	err := c.cc.Invoke(ctx, TutorService_GenerateCramSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GenerateLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LessonResponse)
	err := c.cc.Invoke(ctx, TutorService_GenerateLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GenerateLessonAndExercises(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LessonResponse)
	err := c.cc.Invoke(ctx, TutorService_GenerateLessonAndExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) CheckTopicSufficiency(ctx context.Context, in *SufficiencyRequest, opts ...grpc.CallOption) (*SufficiencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SufficiencyResponse)
	err := c.cc.Invoke(ctx, TutorService_CheckTopicSufficiency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) DeleteClass(ctx context.Context, in *DeleteClassRequest, opts ...grpc.CallOption) (*DeleteClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClassResponse)
	err := c.cc.Invoke(ctx, TutorService_DeleteClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GetSyllabus(ctx context.Context, in *GetSyllabusRequest, opts ...grpc.CallOption) (*GetSyllabusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyllabusResponse)
	err := c.cc.Invoke(ctx, TutorService_GetSyllabus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) EditSyllabus(ctx context.Context, in *EditSyllabusRequest, opts ...grpc.CallOption) (*EditSyllabusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditSyllabusResponse)
	err := c.cc.Invoke(ctx, TutorService_EditSyllabus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TutorServiceServer is the server API for TutorService service.
// All implementations must embed UnimplementedTutorServiceServer
// for forward compatibility.
type TutorServiceServer interface {
	ProcessSyllabus(context.Context, *SyllabusRequest) (*SyllabusResponse, error)
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	SubmitQuizResult(context.Context, *QuizResultRequest) (*QuizResultResponse, error)
	GenerateAdaptiveQuiz(context.Context, *AdaptiveQuizRequest) (*AdaptiveQuizResponse, error)
	GetQuizScores(context.Context, *GetQuizScoresRequest) (*GetQuizScoresResponse, error)
	IngestMaterial(context.Context, *IngestRequest) (*IngestResponse, error)
	GenerateQuiz(context.Context, *QuizRequest) (*QuizResponse, error)
	GenerateCramSession(context.Context, *CramRequest) (*CramResponse, error)
	GenerateLesson(context.Context, *LessonRequest) (*LessonResponse, error)
	GenerateLessonAndExercises(context.Context, *LessonRequest) (*LessonResponse, error)
	CheckTopicSufficiency(context.Context, *SufficiencyRequest) (*SufficiencyResponse, error)
	DeleteClass(context.Context, *DeleteClassRequest) (*DeleteClassResponse, error)
	GetSyllabus(context.Context, *GetSyllabusRequest) (*GetSyllabusResponse, error)
	EditSyllabus(context.Context, *EditSyllabusRequest) (*EditSyllabusResponse, error)
	mustEmbedUnimplementedTutorServiceServer()
}

// UnimplementedTutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTutorServiceServer struct{}

func (UnimplementedTutorServiceServer) ProcessSyllabus(context.Context, *SyllabusRequest) (*SyllabusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessSyllabus not implemented")
}
func (UnimplementedTutorServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedTutorServiceServer) SubmitQuizResult(context.Context, *QuizResultRequest) (*QuizResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitQuizResult not implemented")
}
func (UnimplementedTutorServiceServer) GenerateAdaptiveQuiz(context.Context, *AdaptiveQuizRequest) (*AdaptiveQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateAdaptiveQuiz not implemented")
}
func (UnimplementedTutorServiceServer) GetQuizScores(context.Context, *GetQuizScoresRequest) (*GetQuizScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuizScores not implemented")
}
func (UnimplementedTutorServiceServer) IngestMaterial(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMaterial not implemented")
}
func (UnimplementedTutorServiceServer) GenerateQuiz(context.Context, *QuizRequest) (*QuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateQuiz not implemented")
}
func (UnimplementedTutorServiceServer) GenerateCramSession(context.Context, *CramRequest) (*CramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCramSession not implemented")
}
func (UnimplementedTutorServiceServer) GenerateLesson(context.Context, *LessonRequest) (*LessonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateLesson not implemented")
}
func (UnimplementedTutorServiceServer) GenerateLessonAndExercises(context.Context, *LessonRequest) (*LessonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateLessonAndExercises not implemented")
}
func (UnimplementedTutorServiceServer) CheckTopicSufficiency(context.Context, *SufficiencyRequest) (*SufficiencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTopicSufficiency not implemented")
}
func (UnimplementedTutorServiceServer) DeleteClass(context.Context, *DeleteClassRequest) (*DeleteClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClass not implemented")
}
func (UnimplementedTutorServiceServer) GetSyllabus(context.Context, *GetSyllabusRequest) (*GetSyllabusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyllabus not implemented")
}
func (UnimplementedTutorServiceServer) EditSyllabus(context.Context, *EditSyllabusRequest) (*EditSyllabusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditSyllabus not implemented")
}
func (UnimplementedTutorServiceServer) mustEmbedUnimplementedTutorServiceServer() {}
func (UnimplementedTutorServiceServer) testEmbeddedByValue()                      {}

// UnsafeTutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TutorServiceServer will
// result in compilation errors.
type UnsafeTutorServiceServer interface {
	mustEmbedUnimplementedTutorServiceServer()
}

func RegisterTutorServiceServer(s grpc.ServiceRegistrar, srv TutorServiceServer) {
	// If the following call panics, it indicates UnimplementedTutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TutorService_ServiceDesc, srv)
}

func _TutorService_ProcessSyllabus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyllabusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).ProcessSyllabus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_ProcessSyllabus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).ProcessSyllabus(ctx, req.(*SyllabusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_SubmitQuizResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuizResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).SubmitQuizResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_SubmitQuizResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).SubmitQuizResult(ctx, req.(*QuizResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GenerateAdaptiveQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdaptiveQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GenerateAdaptiveQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GenerateAdaptiveQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GenerateAdaptiveQuiz(ctx, req.(*AdaptiveQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GetQuizScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuizScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GetQuizScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GetQuizScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GetQuizScores(ctx, req.(*GetQuizScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_IngestMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).IngestMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_IngestMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).IngestMaterial(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GenerateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GenerateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GenerateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GenerateQuiz(ctx, req.(*QuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GenerateCramSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GenerateCramSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GenerateCramSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GenerateCramSession(ctx, req.(*CramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GenerateLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GenerateLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GenerateLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GenerateLesson(ctx, req.(*LessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GenerateLessonAndExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GenerateLessonAndExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GenerateLessonAndExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GenerateLessonAndExercises(ctx, req.(*LessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_CheckTopicSufficiency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SufficiencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).CheckTopicSufficiency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_CheckTopicSufficiency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).CheckTopicSufficiency(ctx, req.(*SufficiencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_DeleteClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).DeleteClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_DeleteClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).DeleteClass(ctx, req.(*DeleteClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GetSyllabus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyllabusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GetSyllabus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GetSyllabus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GetSyllabus(ctx, req.(*GetSyllabusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_EditSyllabus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSyllabusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).EditSyllabus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_EditSyllabus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).EditSyllabus(ctx, req.(*EditSyllabusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TutorService_ServiceDesc is the grpc.ServiceDesc for TutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ace.TutorService",
	HandlerType: (*TutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSyllabus",
			Handler:    _TutorService_ProcessSyllabus_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _TutorService_Chat_Handler,
		},
		{
			MethodName: "SubmitQuizResult",
			Handler:    _TutorService_SubmitQuizResult_Handler,
		},
		{
			MethodName: "GenerateAdaptiveQuiz",
			Handler:    _TutorService_GenerateAdaptiveQuiz_Handler,
		},
		{
			MethodName: "GetQuizScores",
			Handler:    _TutorService_GetQuizScores_Handler,
		},
		{
			MethodName: "IngestMaterial",
			Handler:    _TutorService_IngestMaterial_Handler,
		},
		{
			MethodName: "GenerateQuiz",
			Handler:    _TutorService_GenerateQuiz_Handler,
		},
		{
			MethodName: "GenerateCramSession",
			Handler:    _TutorService_GenerateCramSession_Handler,
		},
		{
			MethodName: "GenerateLesson",
			Handler:    _TutorService_GenerateLesson_Handler,
		},
		{
			MethodName: "GenerateLessonAndExercises",
			Handler:    _TutorService_GenerateLessonAndExercises_Handler,
		},
		{
			MethodName: "CheckTopicSufficiency",
			Handler:    _TutorService_CheckTopicSufficiency_Handler,
		},
		{
			MethodName: "DeleteClass",
			Handler:    _TutorService_DeleteClass_Handler,
		},
		{
			MethodName: "GetSyllabus",
			Handler:    _TutorService_GetSyllabus_Handler,
		},
		{
			MethodName: "EditSyllabus",
			Handler:    _TutorService_EditSyllabus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ace.proto",
}
