// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/ace.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TutorService_ProcessSyllabus_FullMethodName = "/ace.TutorService/ProcessSyllabus"
	TutorService_Chat_FullMethodName            = "/ace.TutorService/Chat"
)

// TutorServiceClient is the client API for TutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TutorServiceClient interface {
	ProcessSyllabus(ctx context.Context, in *SyllabusRequest, opts ...grpc.CallOption) (*SyllabusResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type tutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTutorServiceClient(cc grpc.ClientConnInterface) TutorServiceClient {
	return &tutorServiceClient{cc}
}

func (c *tutorServiceClient) ProcessSyllabus(ctx context.Context, in *SyllabusRequest, opts ...grpc.CallOption) (*SyllabusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyllabusResponse)
	err := c.cc.Invoke(ctx, TutorService_ProcessSyllabus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, TutorService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TutorServiceServer is the server API for TutorService service.
// All implementations must embed UnimplementedTutorServiceServer
// for forward compatibility.
type TutorServiceServer interface {
	ProcessSyllabus(context.Context, *SyllabusRequest) (*SyllabusResponse, error)
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	mustEmbedUnimplementedTutorServiceServer()
}

// UnimplementedTutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTutorServiceServer struct{}

func (UnimplementedTutorServiceServer) ProcessSyllabus(context.Context, *SyllabusRequest) (*SyllabusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessSyllabus not implemented")
}
func (UnimplementedTutorServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedTutorServiceServer) mustEmbedUnimplementedTutorServiceServer() {}
func (UnimplementedTutorServiceServer) testEmbeddedByValue()                      {}

// UnsafeTutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TutorServiceServer will
// result in compilation errors.
type UnsafeTutorServiceServer interface {
	mustEmbedUnimplementedTutorServiceServer()
}

func RegisterTutorServiceServer(s grpc.ServiceRegistrar, srv TutorServiceServer) {
	// If the following call panics, it indicates UnimplementedTutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TutorService_ServiceDesc, srv)
}

func _TutorService_ProcessSyllabus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyllabusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).ProcessSyllabus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_ProcessSyllabus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).ProcessSyllabus(ctx, req.(*SyllabusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TutorService_ServiceDesc is the grpc.ServiceDesc for TutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ace.TutorService",
	HandlerType: (*TutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSyllabus",
			Handler:    _TutorService_ProcessSyllabus_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _TutorService_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ace.proto",
}
